name: Android CI/CD Debug Build & Release

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup debug.keystore
        env:
          DEBUG_KEYSTORE_BASE64: ${{ secrets.DEBUG_KEYSTORE_BASE64 }}
          DEBUG_KEYSTORE_PASSWORD: ${{ secrets.DEBUG_KEYSTORE_PASSWORD }}
        run: |
          $keystoreDir = Join-Path $HOME ".android"
          New-Item -ItemType Directory -Force -Path $keystoreDir
          $keystorePath = Join-Path $keystoreDir "debug.keystore"
          $bytes = [System.Convert]::FromBase64String($env:DEBUG_KEYSTORE_BASE64)
          [System.IO.File]::WriteAllBytes($keystorePath, $bytes)
          
          # Validate keystore with keytool
          $keytoolPath = Join-Path $env:JAVA_HOME "bin\keytool.exe"
          $command = "& `"$keytoolPath`" -list -v -keystore `"$keystorePath`" -storepass `"$env:DEBUG_KEYSTORE_PASSWORD`" -noprompt"
          Invoke-Expression $command | Out-Null
          if ($LASTEXITCODE -ne 0) {
            exit 1
          }

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Get Version Name
        id: get_version
        env:
          DEBUG_STORE_PASSWORD: ${{ secrets.DEBUG_STORE_PASSWORD }}
          DEBUG_KEY_ALIAS: ${{ secrets.DEBUG_KEY_ALIAS }}
          DEBUG_KEY_PASSWORD: ${{ secrets.DEBUG_KEY_PASSWORD }}
        run: |
          $rawOutput = ./gradlew.bat :app:printVersionName -q --no-daemon 2>&1
          if ($LASTEXITCODE -ne 0) {
            exit 1
          }
          $parts = $rawOutput.Trim().Split([char[]]' ', [System.StringSplitOptions]::RemoveEmptyEntries)
          $version = $parts[-1]
          echo "version_name=$version" >> $env:GITHUB_OUTPUT

      - name: Build Debug APK
        env:
          DEBUG_KEYSTORE_PASSWORD: ${{ secrets.DEBUG_KEYSTORE_PASSWORD }}
          DEBUG_KEY_ALIAS: ${{ secrets.DEBUG_KEY_ALIAS }}
          DEBUG_KEY_PASSWORD: ${{ secrets.DEBUG_KEY_PASSWORD }}
        run: ./gradlew.bat assembleDebug --no-daemon

      - name: Create Git Tag
        run: |
          $tagName = "${{ steps.get_version.outputs.version_name }}"
          git tag $tagName
          git push origin $tagName

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.version_name }}
          release_name: Release ${{ steps.get_version.outputs.version_name }}
          body: |
            Debug build for version ${{ steps.get_version.outputs.version_name }}
          draft: false
          prerelease: true

      - name: Upload Debug APK to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./app/build/outputs/apk/debug/app-debug.apk
          asset_name: app-debug-${{ steps.get_version.outputs.version_name }}.apk
          asset_content_type: application/vnd.android.package-archive
